name: Convert Markdown

on: [push]

jobs:
  install:
    name: Installing Packages
    runs-on: ubuntu-latest
    steps:
     - name: Markdown to JSON
       uses: ClydeDz/markdown-to-json@v0.1.0
       with:
        settings-json-file: /tarot.json
            
